spring:
  application:
    name:kafka-creditcard-producer

server:
  port:9090
#server.servlet.context-path=/api/

spring:
  zipkin:
    base-url:http://localhost:9411/

  kafka:
    producer:
      bootstrap-servers=localhost:9092
#spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
#spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
