
server:
  port:9090
#server.servlet.context-path=/api/

spring:
  application:
    name:kafka-creditcard-producer

  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  zipkin:
    base-url:http://localhost:9411/

  security:
    user:
      name: ajay
      password : vikas

# All traces should be sent to latency analysis tool
management:
  tracing:
    sampling:
      probability: 1.0

# traceID and spanId are predefined MDC keys - we want the logs to include them
#logging:
#  pattern:
#    level : [${spring.application.name:},%X{traceId:-},%X{spanId:-}]

  kafka:
    producer:
      bootstrap-servers=localhost:9092
#spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
#spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
