version: '3'
service:
  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: http://localhost1:9092,http://localhost2:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: http://localhost1:9092,http://localhost2:9092
      KAFKA_ZOOKEEPER_CONNECT: http://localhost:2181
      #KAFKA_CREATE_TOPICS: "creditcard-payment-topic-event"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock