
--- CREATE TRANSACTION TABLE SCRIPT

CREATE TABLE CREDIT_CARD_TRANSACTION (
  TRANSACTIONID VARCHAR(255) primary key,
  MERCHANTID VARCHAR(255),
  CARDNUMBER NUMERIC,
  AMOUNT NUMERIC(10,2),
  TIMESTAMPINMILLIS TIMESTAMP,
  STATUS VARCHAR(25)
);